version: 2

aliases:
  - &working_directory ~/gonevis-dash  
  - &restore_yarn_cache
    keys: 
      -dependency-cache-{{ checksum "package.json" }}

docker_image_and_WD_env: &docker_image_and_WD_env
  docker:
    - image: circleci/node:8.11.3
  working_directory:  *working_directory


jobs:
  build:
    <<: *docker_image_and_WD_env    
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  jshint:
    <<: *docker_image_and_WD_env    
    steps:
    - checkout
    - restore_cache: *restore_cache
    - run:
        name: code quality
        command: npm run code-quality
  test:
    <<: *docker_image_and_WD_env
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: 'npm run report-coverage'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  deploy:
    <<: *docker_image_and_WD_env    
    steps:
    - checkout
    - restore_cache: *restore_cache
    - run:
        name: Deploying to Production
        command: |
          sudo apt -y install rsync
          ./scripts/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - jshint:
          requires:
            - test
      - deploy:
          requires:
            - build
            - test
            - jshint
          filters:
            branches:
              only: production
